### ISSUE TITLE
Healthbox3ApiClientAuthenticationError

### ISSUE THREAD

**Issue by aphotrax** [rmassch/healthbox-hacs#26]
### Checklist

- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/rmassch/healthbox3/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hi,

I'm using v0.0.8 and I'm unable to get any entities active in my installation (HA 2023.3.6). 
Also tried without the API key but same result, no entities are created like the setup fails.

Hope this helps.

/v2/api/api_key/status
`{"options":{"disable_telemetry_data_allowed":true,"local_sensor_data_allowed":true},"state":"valid"}`

### API output

{"device_type":"HEALTHBOX3","description":"Healthbox 3.0","serial":"XXX","warranty_number":"XXX","global":{"parameter":{"device name":{"unit":"","value":"HEALTHBOX3[XXX]"},"legislation country":{"unit":"","value":"be"},"warranty":{"unit":"","value":"XXX"}}},"room":{"1":{"name":"Keuken","type":"Kitchen","parameter":{"icon":{"unit":"","value":""},"subzone":{"unit":"","value":""},"valve":{"unit":"","value":"3"},"valve_warranty":{"unit":"","value":"KHN253910000P42"},"nominal":{"unit":"m³/h","value":75.0}},"profile_name":"health","actuator":[{"name":"air valve[3]_HealthBox 3[Healthbox3]","type":"air valve","basic_id":3,"parameter":{"flow_rate":{"unit":"m³/h","value":18.75}}}],"sensor":[{"basic_id":3,"name":"indoor temperature[3]_HealthBox 3[Healthbox3]","parameter":{"temperature":{"unit":"deg C","value":19.06919966430152}},"type":"indoor temperature"},{"basic_id":3,"name":"indoor relative humidity[3]_HealthBox 3[Healthbox3]","parameter":{"humidity":{"unit":"pct","value":42.148470283054859}},"type":"indoor relative humidity"},{"basic_id":3,"name":"indoor air quality index[3]_HealthBox 3[Healthbox3]","parameter":{"index":{"unit":"","value":30.833333333333337},"main_pollutant":{"unit":"","value":""}},"type":"indoor air quality index"},{"basic_id":3,"name":"indoor CO2[3]_HealthBox 3[Healthbox3]","parameter":{"concentration":{"unit":"ppm","value":570.0}},"type":"indoor CO2"}]},"2":{"name":"Bijkeuken","type":"LaundryRoom","parameter":{"icon":{"unit":"","value":""},"subzone":{"unit":"","value":""},"valve":{"unit":"","value":"4"},"valve_warranty":{"unit":"","value":"KHN580490000G09"},"nominal":{"unit":"m³/h","value":50.0}},"profile_name":"health","actuator":[{"name":"air valve[4]_HealthBox 3[Healthbox3]","type":"air valve","basic_id":4,"parameter":{"flow_rate":{"unit":"m³/h","value":12.5}}}],"sensor":[{"basic_id":4,"name":"indoor temperature[4]_HealthBox 3[Healthbox3]","parameter":{"temperature":{"unit":"deg C","value":18.50041962310216}},"type":"indoor temperature"},{"basic_id":4,"name":"indoor relative humidity[4]_HealthBox 3[Healthbox3]","parameter":{"humidity":{"unit":"pct","value":44.199282825970858}},"type":"indoor relative humidity"},{"basic_id":4,"name":"indoor CO2[4]_HealthBox 3[Healthbox3]","parameter":{},"type":"indoor CO2"},{"basic_id":4,"name":"indoor air quality index[4]_HealthBox 3[Healthbox3]","parameter":{"index":{"unit":"","value":8.523793181099585},"main_pollutant":{"unit":"","value":""}},"type":"indoor air quality index"}]},"3":{"name":"Toilet beneden","type":"Toilet","parameter":{"icon":{"unit":"","value":""},"offset":{"unit":"","value":0.0},"subzone":{"unit":"","value":"[]\n"},"valve":{"unit":"","value":"5"},"valve_warranty":{"unit":"","value":"KZ7529800000A07"},"nominal":{"unit":"m³/h","value":25.0}},"profile_name":"health","actuator":[{"name":"air valve[5]_HealthBox 3[Healthbox3]","type":"air valve","basic_id":5,"parameter":{"flow_rate":{"unit":"m³/h","value":6.25}}}],"sensor":[{"basic_id":5,"name":"indoor temperature[5]_HealthBox 3[Healthbox3]","parameter":{"temperature":{"unit":"deg C","value":18.609903105210959}},"type":"indoor temperature"},{"basic_id":5,"name":"indoor relative humidity[5]_HealthBox 3[Healthbox3]","parameter":{"humidity":{"unit":"pct","value":43.01060502021821}},"type":"indoor relative humidity"},{"basic_id":5,"name":"indoor volatile organic compounds[5]_HealthBox 3[Healthbox3]","parameter":{"concentration":{"unit":"ppm","value":510.2315680000029},"concentration_maximum":{"unit":"ppm","value":624.7487734918104},"raw":{"unit":"ppm","value":51121.0}},"type":"indoor volatile organic compounds"},{"basic_id":5,"name":"indoor air quality index[5]_HealthBox 3[Healthbox3]","parameter":{"index":{"unit":"","value":33.333333333333339},"main_pollutant":{"unit":"","value":""}},"type":"indoor air quality index"}]},"4":{"name":"Toilet boven","type":"Toilet","parameter":{"icon":{"unit":"","value":""},"offset":{"unit":"","value":0.0},"subzone":{"unit":"","value":"[]\n"},"valve":{"unit":"","value":"6"},"valve_warranty":{"unit":"","value":"KHN179220000G03"},"nominal":{"unit":"m³/h","value":25.0}},"profile_name":"health","actuator":[{"name":"air valve[6]_HealthBox 3[Healthbox3]","type":"air valve","basic_id":6,"parameter":{"flow_rate":{"unit":"m³/h","value":6.25}}}],"sensor":[{"basic_id":6,"name":"indoor temperature[6]_HealthBox 3[Healthbox3]","parameter":{"temperature":{"unit":"deg C","value":18.41763942931258}},"type":"indoor temperature"},{"basic_id":6,"name":"indoor relative humidity[6]_HealthBox 3[Healthbox3]","parameter":{"humidity":{"unit":"pct","value":48.10101472495613}},"type":"indoor relative humidity"},{"basic_id":6,"name":"indoor volatile organic compounds[6]_HealthBox 3[Healthbox3]","parameter":{"concentration":{"unit":"ppm","value":493.4393313305336},"concentration_maximum":{"unit":"ppm","value":626.5824442030935},"raw":{"unit":"ppm","value":49904.0}},"type":"indoor volatile organic compounds"},{"basic_id":6,"name":"indoor air quality index[6]_HealthBox 3[Healthbox3]","parameter":{"index":{"unit":"","value":33.333333333333339},"main_pollutant":{"unit":"","value":""}},"type":"indoor air quality index"}]},"5":{"name":"Badkamer","type":"BathRoom","parameter":{"icon":{"unit":"","value":"BathRoom"},"offset":{"unit":"","value":0.0},"subzone":{"unit":"","value":"[]\n"},"valve":{"unit":"","value":"7"},"valve_warranty":{"unit":"","value":"KHN466400000A44"},"nominal":{"unit":"m³/h","value":50.0}},"profile_name":"health","actuator":[{"name":"air valve[7]_HealthBox 3[Healthbox3]","type":"air valve","basic_id":7,"parameter":{"flow_rate":{"unit":"m³/h","value":49.205230116448138}}}],"sensor":[{"basic_id":7,"name":"indoor temperature[7]_HealthBox 3[Healthbox3]","parameter":{"temperature":{"unit":"deg C","value":21.579308766308079}},"type":"indoor temperature"},{"basic_id":7,"name":"indoor relative humidity[7]_HealthBox 3[Healthbox3]","parameter":{"humidity":{"unit":"pct","value":49.451438162813769}},"type":"indoor relative humidity"},{"basic_id":7,"name":"indoor volatile organic compounds[7]_HealthBox 3[Healthbox3]","parameter":{"concentration":{"unit":"ppm","value":450.0},"concentration_maximum":{"unit":"ppm","value":1706.8993739413564},"raw":{"unit":"ppm","value":51442.0}},"type":"indoor volatile organic compounds"},{"basic_id":7,"name":"indoor air quality index[7]_HealthBox 3[Healthbox3]","parameter":{"index":{"unit":"","value":74.11692235160905},"main_pollutant":{"unit":"","value":"indoor volatile organic compounds"}},"type":"indoor air quality index"}]}},"sensor":[{"name":"global air quality index","type":"global air quality index","basic_id":0,"parameter":{"index":{"unit":"","value":74.11692235160905},"main_pollutant":{"unit":"","value":"indoor volatile organic compounds"},"room":{"unit":"","value":"Badkamer"}}}]}

### Debug logs

```text
2023-04-01 15:20:48.677 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.1.18 for healthbox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/healthbox/__init__.py", line 37, in async_setup_entry
    await api.async_enable_advanced_api_features()
  File "/usr/local/lib/python3.10/site-packages/pyhealthbox3/healthbox3.py", line 122, in async_enable_advanced_api_features
    raise Healthbox3ApiClientAuthenticationError
pyhealthbox3.healthbox3.Healthbox3ApiClientAuthenticationError
```

**Comment by rmassch** [comment]
@aphotrax when I serve your config through my "simulator" I do not get the authentication error. Your status also shows that your API key is valid (which is good)
However it did provide me with another issue and hopefully that is the issue causing your issue in the background.

![image](https://user-images.githubusercontent.com/1083135/229482316-2bb5701b-8abd-4867-b683-d9f0bf7a2dc5.png)

For each room, in my device, I have an nominal value, an offset and an air valve flow rate.
However, on your device, there is no offset.

I'll try to work around this and provide a fix for the missing offset asap and hopefully that allows your device to be added.
But you'll have to check if the ventilation rate is correct (should you be able to add the device).

**Comment by rmassch** [comment]
Great to hear that it works.
Were you able to verify the ventilation rate?

**Comment by aphotrax** [comment]
It corresponds to the Renson App so I'd say the calculations are correct.

Op ma 3 apr. 2023 19:21 schreef rmassch ***@***.***>:
