### ISSUE TITLE
Task exception was never retrieved - IndexError

### ISSUE THREAD

**Issue by tvanhove** [rmassch/healthbox-hacs#47]
### Checklist

- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/rmassch/healthbox3/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I had an issue where I was not able to change the boost level in different rooms, but while checking the logs I found these recurring errors. I am talking 10s of times in a couple of minutes and continuously increasing.

All sensors are showing up, except for one room, where all sensors are unavailable. Could this be the sensors/entities it is trying to create, but unable to do so?

Happy to provide further info, if required. Log added below.

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 229, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 431, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 469, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/healthbox/sensor.py", line 334, in native_value
    self.coordinator.api.rooms[int(self.entity_description.room.room_id) - 1]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
```

**Comment by rmassch** [comment]
Hi @tvanhove,

Did the integration work before or is this the first time setting up?

Can you provide me the output of browsing to http://IP_OF_YOUR_HEALTHBOX/v2/api/data/current ?

**Comment by tvanhove** [comment]
Hi @rmassch 

First time setting up. I am doing this remote, but will try to get the output ASAP.

**Comment by tvanhove** [comment]
@rmassch got it right here

```
{"device_type":"HEALTHBOX3","description":"Healthbox 3.0","serial":"210817P0288","warranty_number":"XUD025750014C27","global":{"parameter":{"device name":{"unit":"","value":"HEALTHBOX3[XUD025750014C27]"},"legislation country":{"unit":"","value":"be"},"warranty":{"unit":"","value":"XUD025750014C27"}}},"room":{"1":{"name":"Slaapkamer/Dressing","type":"BedRoom","parameter":{"doors_open":{"unit":"","value":true},"doors_present":{"unit":"","value":true},"icon":{"unit":"","value":""},"measured_power":{"unit":"","value":0.0},"measured_voltage":{"unit":"","value":0.0},"measurement":{"unit":"","value":-1.0},"offset":{"unit":"","value":0.0},"subzone":{"unit":"","value":"[]\n"},"valve":{"unit":"","value":"1"},"valve_warranty":{"unit":"","value":"LTV345740004M43"},"nominal":{"unit":"m³/h","value":35.0}},"profile_name":"health","actuator":[{"name":"air valve[1]_HealthBox 3[Healthbox3]","type":"air valve","basic_id":1,"parameter":{"flow_rate":{"unit":"m³/h","value":5.0}}}],"sensor":[{"basic_id":1,"name":"indoor temperature[1]_HealthBox 3[Healthbox3]","parameter":{"temperature":{"unit":"deg C","value":31.6411078049897}},"type":"indoor temperature"},{"basic_id":1,"name":"indoor relative humidity[1]_HealthBox 3[Healthbox3]","parameter":{"humidity":{"unit":"pct","value":30.25101091020065}},"type":"indoor relative humidity"},{"basic_id":1,"name":"indoor CO2[1]_HealthBox 3[Healthbox3]","parameter":{"concentration":{"unit":"ppm","value":502.0}},"type":"indoor CO2"},{"basic_id":1,"name":"indoor air quality index[1]_HealthBox 3[Healthbox3]","parameter":{"index":{"unit":"","value":46.05461561299234},"main_pollutant":{"unit":"","value":"indoor relative humidity"}},"type":"indoor air quality index"}]},"2":{"name":"Keuken (open)","type":"Kitchen","parameter":{"icon":{"unit":"","value":""},"measurement":{"unit":"","value":-1.0},"offset":{"unit":"","value":0.0},"subzone":{"unit":"","value":"[]\n"},"valve":{"unit":"","value":"2"},"valve_warranty":{"unit":"","value":"LTV157620004H04"},"nominal":{"unit":"m³/h","value":62.0}},"profile_name":"health","actuator":[{"name":"air valve[2]_HealthBox 3[Healthbox3]","type":"air valve","basic_id":2,"parameter":{"flow_rate":{"unit":"m³/h","value":6.2}}}],"sensor":[{"basic_id":2,"name":"indoor temperature[2]_HealthBox 3[Healthbox3]","parameter":{"temperature":{"unit":"deg C","value":31.026932173647667}},"type":"indoor temperature"},{"basic_id":2,"name":"indoor relative humidity[2]_HealthBox 3[Healthbox3]","parameter":{"humidity":{"unit":"pct","value":30.867475394827193}},"type":"indoor relative humidity"},{"basic_id":2,"name":"indoor CO2[2]_HealthBox 3[Healthbox3]","parameter":{"concentration":{"unit":"ppm","value":494.0}},"type":"indoor CO2"},{"basic_id":2,"name":"indoor air quality index[2]_HealthBox 3[Healthbox3]","parameter":{"index":{"unit":"","value":43.11687945473427},"main_pollutant":{"unit":"","value":"indoor relative humidity"}},"type":"indoor air quality index"}]},"3":{"name":"Wasplaats","type":"Kitchen","parameter":{"icon":{"unit":"","value":"LaundryRoom"},"measurement":{"unit":"","value":-1.0},"offset":{"unit":"","value":0.0},"subzone":{"unit":"","value":"[]\n"},"valve":{"unit":"","value":"3"},"valve_warranty":{"unit":"","value":"LTV157620004H54"},"nominal":{"unit":"m³/h","value":50.0}},"profile_name":"health","actuator":[{"name":"air valve[3]_HealthBox 3[Healthbox3]","type":"air valve","basic_id":3,"parameter":{"flow_rate":{"unit":"m³/h","value":5.0}}}],"sensor":[{"basic_id":3,"name":"indoor temperature[3]_HealthBox 3[Healthbox3]","parameter":{"temperature":{"unit":"deg C","value":30.41809719996948}},"type":"indoor temperature"},{"basic_id":3,"name":"indoor relative humidity[3]_HealthBox 3[Healthbox3]","parameter":{"humidity":{"unit":"pct","value":31.53734645609217}},"type":"indoor relative humidity"},{"basic_id":3,"name":"indoor CO2[3]_HealthBox 3[Healthbox3]","parameter":{"concentration":{"unit":"ppm","value":489.0}},"type":"indoor CO2"},{"basic_id":3,"name":"indoor air quality index[3]_HealthBox 3[Healthbox3]","parameter":{"index":{"unit":"","value":40.30586050718794},"main_pollutant":{"unit":"","value":"indoor relative humidity"}},"type":"indoor air quality index"}]},"4":{"name":"Badkamer","type":"LaundryRoom","parameter":{"icon":{"unit":"","value":""},"measurement":{"unit":"","value":-1.0},"offset":{"unit":"","value":0.0},"subzone":{"unit":"","value":"[]\n"},"valve":{"unit":"","value":"5"},"valve_warranty":{"unit":"","value":"XUD087830004C72"},"nominal":{"unit":"m³/h","value":65.0}},"profile_name":"health","actuator":[{"name":"air valve[5]_HealthBox 3[Healthbox3]","type":"air valve","basic_id":5,"parameter":{"flow_rate":{"unit":"m³/h","value":6.5}}}],"sensor":[{"basic_id":5,"name":"indoor temperature[5]_HealthBox 3[Healthbox3]","parameter":{"temperature":{"unit":"deg C","value":29.387350270847639}},"type":"indoor temperature"},{"basic_id":5,"name":"indoor relative humidity[5]_HealthBox 3[Healthbox3]","parameter":{"humidity":{"unit":"pct","value":32.7367055771725}},"type":"indoor relative humidity"},{"basic_id":5,"name":"indoor air quality index[5]_HealthBox 3[Healthbox3]","parameter":{"index":{"unit":"","value":36.35778718095237},"main_pollutant":{"unit":"","value":""}},"type":"indoor air quality index"}]},"6":{"name":"Toilet","type":"Toilet","parameter":{"icon":{"unit":"","value":""},"measurement":{"unit":"","value":-1.0},"offset":{"unit":"","value":0.0},"subzone":{"unit":"","value":"[]\n"},"valve":{"unit":"","value":"7"},"valve_warranty":{"unit":"","value":"XUD102310004A12"},"nominal":{"unit":"m³/h","value":15.0}},"profile_name":"health","actuator":[{"name":"air valve[7]_HealthBox 3[Healthbox3]","type":"air valve","basic_id":7,"parameter":{"flow_rate":{"unit":"m³/h","value":5.0}}}],"sensor":[{"basic_id":7,"name":"indoor temperature[7]_HealthBox 3[Healthbox3]","parameter":{"temperature":{"unit":"deg C","value":29.173723964293886}},"type":"indoor temperature"},{"basic_id":7,"name":"indoor relative humidity[7]_HealthBox 3[Healthbox3]","parameter":{"humidity":{"unit":"pct","value":34.63035019455253}},"type":"indoor relative humidity"},{"basic_id":7,"name":"indoor volatile organic compounds[7]_HealthBox 3[Healthbox3]","parameter":{"concentration":{"unit":"ppm","value":762.363200000007},"concentration_maximum":{"unit":"ppm","value":762.363200000007},"raw":{"unit":"ppm","value":36451.0}},"type":"indoor volatile organic compounds"},{"basic_id":7,"name":"indoor air quality index[7]_HealthBox 3[Healthbox3]","parameter":{"index":{"unit":"","value":37.96296296296296},"main_pollutant":{"unit":"","value":""}},"type":"indoor air quality index"}]}},"sensor":[{"name":"global air quality index","type":"global air quality index","basic_id":0,"parameter":{"index":{"unit":"","value":46.16904908017466},"main_pollutant":{"unit":"","value":"indoor relative humidity"},"room":{"unit":"","value":"Slaapkamer/Dressing"}}}]}
```

**Comment by rmassch** [comment]
Thanks, hopefully that'll reproduce the same error on my side so I can troubleshoot.
I'll have a look at it whenever I have some spare time and keep you posted

**Comment by rmassch** [comment]
Can you try the beta release I just put up? :)
You might need to enable beta releases in HACS if you haven't done so already

https://github.com/rmassch/healthbox-hacs/releases/tag/v0.0.11-beta

**Comment by tvanhove** [comment]
Yup! That did it. I am seeing info in Toilet and still have full control over the boost function! 

What a speedy fix! Thank you so much, for both the help and the integration

**Comment by rmassch** [comment]
Glad to be of help.

I'll leave this open for a couple of days to see if any issues pop up and then release it fully
